# Generated by Django 6.0 on 2025-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('genres', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
