# Generated by Django 6.0 on 2025-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favorite_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
